### ISSUE TITLE
Support ByteArray in findSchema

### ISSUE THREAD

**Issue by TobiasWalle** [derveloper/kotlin-openapi3-dsl#4]
Currently the "ByteArray" is not supported by the "findSchema" function.

I propose the add the following mapping
```kotlin
when (clazz) {
  // ...
  ByteArray::class-> StringSchema().format("binary")
  // ...
}
```

This would be compliant with the [documentation](https://swagger.io/docs/specification/data-models/data-types/#file).

I could create a PR for this if the solution is accepted.

**Comment by derveloper** [comment]
Hi!

LGTM, looking forward to merge your PR!

**Comment by TobiasWalle** [comment]
@derveloper Perfect! I will probably create the PR next week.
