### ISSUE TITLE
swagger libraries at runtime

### ISSUE THREAD

**Issue by dcheng45** [derveloper/kotlin-openapi3-dsl#7]
With this updated version, my application is no longer compiling the swagger classes because they are being used at runtime now. I see in your gradle file that you changed them from 'compile' to 'implementation'. In my maven dependency tree it used to be 'io.swagger.core.v3:swagger-core...:compile'. Now it says 'io.swagger.core.v3:swagger-core...:runtime. Would you be wiling to change libraries back to compile scope instead of runtime scope. If not then you can go ahead and close this issue.

**Comment by derveloper** [comment]
Hi,

thanks for your finding, I changed the configuration type to `api` and made a new patch release, please try if it works for you, if you're using bintray or jcenter you can fetch the release immediately, otherwise you need to wait or build it on your own.

**Comment by dcheng45** [comment]
Thanks. For now I've added the swagger library to my dependency management section and overrode scope to compile
